#!/bin/sh
# Cleanly TERM & wait;
# see https://github.com/ewindisch/container-shpid1
trap clean_exit EXIT
function clean_exit {
 local pids=$(jobs -p)
 if [[ "$pids" != "" ]]; then
  kill $pids 2>/dev/null || :
 fi
 wait $pids 2>/dev/null
}
